import = [
  "~/.config/alacritty/catpuccin-macchiato.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window]
opacity = 1

[window.padding]
x = 15
y = 15
